routes.py
from flask import Blueprint, render_template, redirect, request, url_for, session, flash
from model import get_password, update_password, update_email, save_user, post_image, get_username_count
from model import get_details, get_post_count, get_images_data, get_last_post
from modules import get_image_path_and_name, read_image, unserialize_models, image_src, serialize_image
from modules import datagenerator, prediction_string, get_cropped_image, resize_image, get_image_src
from werkzeug.utils import secure_filename
import os


main = Blueprint('main', __name__, static_folder='static', template_folder='templates')
UPLOAD_FOLDER = 'static/files'
age_model, gender_model, age_class_model = unserialize_models()

@main.route('/', methods=['GET', 'POST'])
@main.route('/signin', methods=['GET', 'POST'])
def signin():
    try:
        if request.method == 'POST':
            username = str(request.form['username'])
            password = str(request.form['password'])
            if get_username_count(username) == 1:
                con_password = get_password(username)
                if password == con_password:
                    page_name = 'main.homepage'
                    message = 'Signed in Successfully'
                    session.permanent = True
                    session['username'] = username
                    session['password'] = password
                    flash(message, 'success')
                    return redirect(url_for(page_name))
                else:
                    page_name = 'signin.html'
                    message = 'Password mismatch'
                    flash(message, 'danger')
                    return redirect(request.url)
            else:
                page_name = 'main.signup'
                message = 'Username doesn\'t exist please create an account' 
                flash(message, 'danger')
                return redirect(url_for(page_name))
        else:
            if 'username' in session:
                flash('User already signed in', 'danger')
                return redirect(url_for('main.homepage'))
            return render_template('signin.html')
    except:
        flash('No Internet Connection Try Again', 'danger')
        return render_template('signin.html')


@main.route('/signup', methods=['GET', 'POST'])
def signup():
    try:
        if request.method == 'POST':
            username = str(request.form['username'])
            email = str(request.form['email'])
            password = str(request.form['password'])
            confirm_password = str(request.form['confirm_password'])
            if username == '' or email == '' or password == '' or confirm_password == '':
                page_name = 'signup.html'
                message = 'Input Fields or Field Empty'
                flash(message, 'danger')
                return redirect(request.url)
            elif password != confirm_password:
                page_name = 'signup.html'
                message = 'Passwords Don\'t match'
                flash(message, 'danger')
                return redirect(request.url)
            elif password == confirm_password and len(password) >= 8:
                if get_username_count(username) == 0:
                    page_name = 'main.signin'
                    message = 'Account Created Successfully'
                    save_user(username, email, password)
                    flash(message, 'success')
                    return redirect(url_for(page_name))
                else:
                    page_name = 'main.signin'
                    message = 'Username exist please sign in'
                    flash(message, 'danger')
                    return redirect(url_for(page_name))
            elif password == confirm_password and len(password) < 8:
                page_name = 'signup.html'
                message = 'Password must be 8 or more characters long' 
                flash(message, 'danger')
                return redirect(request.url) 
        else:
            if 'username' in session:
                flash('User already signed in', 'danger')
                return redirect(url_for('main.homepage'))
            return render_template('signup.html')
    except:
        return render_template('signup.html')


@main.route('/homepage', methods=['GET', 'POST'])
def homepage():
    if 'username' in session:
        if request.method == 'GET':
            username = session['username']
            return render_template('homepage.html', username=username)
    else:
        flash('Please sign in', 'danger')
        return redirect(url_for('main.signin')) 
       

@main.route('/predict', methods=['GET', 'POST'])
def predict():
    try:
        if 'username' in session:
            if request.method == 'POST': 
                image = request.files['file']
                image_extension = str(image.filename).split('.')[-1]
                image_extensions = ['jpeg', 'jpg', 'jpe', 'jp2', 'png', 'btmp', 'dib', 'webp', 'pbm', 'pgm', 'ppm', 'pxm', 'pnm']
                if image_extension.lower() not in image_extensions:
                    message = 'File Selected Was Not An Image'
                    flash(message, 'danger')
                    return redirect(url_for('main.homepage'))
                else:
                    image.save(os.path.join(os.path.abspath(os.path.dirname(__file__)), UPLOAD_FOLDER, secure_filename(image.filename)))
                    image_name, image_path = get_image_path_and_name()
                    cropped_image = get_cropped_image(image_path)
                    if cropped_image is None:
                        message = 'Image Has No Face In It'
                        os.remove(image_path)
                        flash(message, 'danger')
                        return redirect(url_for('main.homepage'))
                    else:
                        image = read_image(image_path)
                        image = resize_image(image)
                        serialized_image = serialize_image(image)
                        X = datagenerator(cropped_image)
                        pred = prediction_string(age_model, age_class_model, gender_model, X)
                        pred = pred.split(',')
                        username = session['username']
                        try:
                            post_image(image_name, serialized_image, pred, username)
                            message = 'Uploaded Image Result'
                        except:
                            message = 'Image exist in database'
                        img_src = image_src(image_path, image_extension, 'path')
                        dic = {
                            'message': message,
                            'image': img_src,
                            'prediction': {
                                'age': pred[0],
                                'gender': pred[1],
                                'age class': pred[2]
                            },
                            'username': username
                        }
                        data = []
                        data.append(dic)
                        return render_template('predict.html', data=data)
            else:
                username = session['username']
                try:
                    uploads_num = get_post_count(username)
                except:
                    flash('No Internet connection Try Again', 'danger')
                    return redirect(url_for('main.homepage'))
                if  uploads_num != 0:
                    data = get_last_post(username)
                    data = get_image_src(data, username)
                    data = data[:-1]
                    data[0]['username'] = username
                    data[0]['message'] = 'Last Uploaded Image'
                    return render_template('predict.html', data=data)
                else:
                    flash('No Uploads Yet', 'danger')
                    return redirect(url_for('main.homepage'))
        else:
            flash('Please sign in', 'danger')
            return redirect(url_for('main.signin'))           
    except:
        page_name = 'predict.html'
        username = session['username']
        data = {
            'username': username
        }
        return render_template(page_name, data=data)
    

@main.route('/change password', methods=['GET', 'POST'])
def changepassword():
    try: 
        if 'username' in session: 
            if request.method == 'POST':
                password = str(request.form['password'])
                new_password = str(request.form['confirm_password'])
                con_password = str(session['password'])
                username = str(session['username'])
                if password != con_password:
                    message = 'Password Mismatch'
                    flash(message, 'danger')
                    return redirect(request.url)
                else:
                    update_password(new_password, username)
                    message = 'Password Was Changed Successfully'
                    flash(message, 'success')
                    return redirect(url_for('main.homepage'))
            else:
                username = session['username']
                data = {
                    'username': username
                }
                return render_template('changepassword.html', data=data)
        else:
            flash('Please sign in', 'danger')
            return redirect(url_for('main.signin')) 
    except:
        message = 'An Error Occurred'
        data = {
                    'username': username,
                    'message': message
                }
        return render_template('changepassword.html', data=data)



templates/changepassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Change Password</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <link rel="stylesheet" href="{{url_for('static', filename='css/style1.css')}}">
</head>
<body>
    <div>
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid">
                <label class="logo">{{ data['username'] }}</label>
                <button
                  class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar"
                  aria-label="Toggle navigation" >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Menu</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                        <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('main.homepage') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.predict') }}">Predict</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('main.details') }}">Display Details</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('main.editemail') }}">Edit Email</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="#">Change Password</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('main.signout') }}">Signout</a>
                        </li>
                    </ul>
                </div>
              </div>
            </div>
        </nav>
    </div>
    <div class="container-sm">
        <div class="row">
            <div class="col-sm-4">
                {% with messages = get_flashed_messages(category_filter=["success"]) %}  
                    {% if messages %} 
                        {% for msg in messages %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                <span>{{ msg }}</span>
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}  
            </div>  
            <div class="col-sm-4">
                {% with messages = get_flashed_messages(category_filter=["danger"]) %}  
                    {% if messages %} 
                        {% for msg in messages %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <span>{{ msg }}</span>
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %} 
            </div>
        </div> 
    </div>
    {% if data['message'] %}
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <span>{{ data['message'] }}</span>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div> 
            </div>  
        </div>
    </div>
{% endif %}
    <div id="main">
        <h2>Change  User's  Password</h2>
        <div id="Forms">
            <form action="{{url_for('main.changepassword')}}" method="post" class="sigup">
                <label for="password">Password</label>
                <input type="password" name="password" id="" placeholder="Enter Your Password">
                <label for="new_password">New Password</label>
                <input type="password" name="confirm_password" id="" placeholder="Enter A New Password">
                <button type="submit">Change Password</button>
            </form>
        </div>
    </div>
</body>
</html>

templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Display Details</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <link rel="stylesheet" href="{{url_for('static', filename='css/style1.css')}}">
</head>
<body>
    <div>
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid">
                <label class="logo">{{ data['username'] }}</label>
                <button
                  class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar"
                  aria-label="Toggle navigation" >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Menu</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                        <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('main.homepage') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.predict') }}">Predict</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="#">Display Details</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('main.editemail') }}">Edit Email</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('main.changepassword') }}">Change Password</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('main.signout') }}">Signout</a>
                        </li>
                    </ul>
                </div>
              </div>
            </div>
        </nav>
    </div>
    {% if data['message'] %}
        <div class="container-sm">
            <div class="row">
                <div class="col-sm-4">
                    <div class="alert alert-{{ data['category'] }} alert-dismissible fade show" role="alert">
                        <span>{{ data['message'] }}</span>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div> 
                </div>  
            </div>
        </div>
    {% endif %}
    <div class="details">
        <div id="details_content">
            <div id="details_info">
                <h2>User's  Personal Info</h2>
                <table class="table table-hover ">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            {% for key in data.keys() %}
                                {% if key == 'username' or key == 'email' or key == 'Number Of Uploads' %}
                                <th scope="col">{{ key }}</th>
                                {% endif %}
                            {% endfor %}
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">1</th>
                            {% for key, value in data.items() %}
                                {% if key == 'username' or key == 'email' or key == 'Number Of Uploads' %}
                                    <td>{{ value }}</td>
                                {% endif %}
                            {% endfor %}
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div id="images">
            {% for key, value in data.items() %}
                {% if key == 'image' %} 
                    {% for i in range(data['size']) %}
                        <div class="main_image">
                            <div>
                                <table class="table table-hover ">
                                    <thead>
                                        <tr>
                                            <th scope="col">#</th>
                                            {% for pred_key in data['prediction'][i].keys() %}
                                                <th scope="col">{{ pred_key }}</th>
                                            {% endfor %}
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <th scope="row">1</th>
                                            {% for pred_val in data['prediction'][i].values() %}
                                                    <td>{{ pred_val }}</td>
                                            {% endfor %}
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div id="user_image">
                                <img src="{{ data['image'][i] }}" alt="image">  
                            </div>   
                        </div>
                    {% endfor %}
                {% endif %}
            {% endfor %}
        </div>
    </div>
</body>
</html>

templates/editmail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Email</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <link rel="stylesheet" href="{{url_for('static', filename='css/style1.css')}}">
</head>
<body>
    <div>
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid">
                <label class="logo">{{ data['username'] }}</label>
                <button
                  class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar"
                  aria-label="Toggle navigation" >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Menu</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                        <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('main.homepage') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.predict') }}">Predict</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('main.details') }}">Display Details</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="#">Edit Email</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('main.changepassword') }}">Change Password</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('main.signout') }}">Signout</a>
                        </li>
                    </ul>
                </div>
              </div>
            </div>
        </nav>
    </div>
    <div class="container-sm">
        <div class="row">
            <div class="col-sm-4">
                {% with messages = get_flashed_messages(category_filter=["success"]) %}  
                    {% if messages %} 
                        {% for msg in messages %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                <span>{{ msg }}</span>
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}  
            </div>  
            <div class="col-sm-4">
                {% with messages = get_flashed_messages(category_filter=["danger"]) %}  
                    {% if messages %} 
                        {% for msg in messages %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <span>{{ msg }}</span>
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %} 
            </div>
        </div> 
    </div>
    <div id="main">
        <h2>Edit  User's  Email</h2>
        <div id="Forms">
            <form action="{{url_for('main.editemail')}}" method="post" class="sigup">
                <label for="password">Password</label>
                <input type="password" name="password" id="" placeholder="Enter Your Password">
                <label for="email">Email</label>
                <input type="email" name="email" id="" placeholder="Enter Your Email">
                <button type="submit">Edit Email</button>
            </form>
        </div>
    </div>
</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HomePage</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <link rel="stylesheet" href="{{url_for('static', filename='css/style1.css')}}">
</head>
<body>
    <div>
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid">
                <label class="logo">{{ username }}</label>
                <button
                  class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar"
                  aria-label="Toggle navigation" >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Menu</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                        <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="#">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.predict') }}">Predict</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('main.details') }}">Display Details</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('main.editemail') }}">Edit Email</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('main.changepassword') }}">Change Password</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('main.signout') }}">Signout</a>
                        </li>
                    </ul>
                </div>
              </div>
            </div>
        </nav>
    </div>
    <div class="container-sm">
        <div class="row">
            <div class="col-sm-4">
                {% with messages = get_flashed_messages(category_filter=["success"]) %}  
                    {% if messages %} 
                        {% for msg in messages %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                <span>{{ msg }}</span>
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}  
            </div>  
            <div class="col-sm-4">
                {% with messages = get_flashed_messages(category_filter=["danger"]) %}  
                    {% if messages %} 
                        {% for msg in messages %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <span>{{ msg }}</span>
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %} 
            </div>
        </div> 
    </div>
    <div id="main">
        <div id="Forms">
            <form action="{{url_for('main.predict')}}" method="post" enctype="multipart/form-data">
                <label for="file">Choose an Image File</label>
                <input type="file" name="file" id="file">
                <button type="submit">Submit</button>
            </form>
        </div>
    </div>
</body>
</html>